"""Geolocation, Companies

Revision ID: 2001fdefaa7e
Revises: 84ae0c957a5
Create Date: 2016-09-01 16:30:20.397625

"""

# revision identifiers, used by Alembic.
revision = '2001fdefaa7e'
down_revision = '84ae0c957a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('technologies', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=1024), nullable=False),
    sa.Column('address_is_valid', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('phone', sa.String(length=1024), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geolocation_is_valid', sa.Boolean(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'jobs', sa.Column('address_is_valid', sa.Boolean(), nullable=False))
    op.add_column(u'jobs', sa.Column('geolocation_is_valid', sa.Boolean(), nullable=False))
    op.add_column(u'jobs', sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column(u'jobs', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=False))
    op.add_column(u'jobs', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column(u'jobs', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column(u'jobs', sa.Column('pushed_on_twitter', sa.Boolean(), nullable=False))
    op.alter_column(u'jobs', 'publication_datetime_is_fake',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'jobs', 'publication_datetime_is_fake',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column(u'jobs', 'pushed_on_twitter')
    op.drop_column(u'jobs', 'longitude')
    op.drop_column(u'jobs', 'latitude')
    op.drop_column(u'jobs', 'last_sync')
    op.drop_column(u'jobs', 'last_modified')
    op.drop_column(u'jobs', 'geolocation_is_valid')
    op.drop_column(u'jobs', 'address_is_valid')
    op.drop_table('companies')
    ### end Alembic commands ###
