"""with address

Revision ID: 2c738e5fe131
Revises: 697e41afa2a
Create Date: 2015-10-20 00:35:23.235267

"""

# revision identifiers, used by Alembic.
revision = '2c738e5fe131'
down_revision = '697e41afa2a'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('address', sa.String(length=1024), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'address')
    ### end Alembic commands ###
