"""without uid

Revision ID: 454ccccb5769
Revises: 2c738e5fe131
Create Date: 2015-10-20 00:37:37.474197

"""

# revision identifiers, used by Alembic.
revision = '454ccccb5769'
down_revision = '2c738e5fe131'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'jobs_uid_key', 'jobs', type_='unique')
    op.drop_column('jobs', 'uid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('uid', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'jobs_uid_key', 'jobs', ['uid'])
    ### end Alembic commands ###
