"""new

Revision ID: 697e41afa2a
Revises: None
Create Date: 2015-10-19 22:31:33.811945

"""

# revision identifiers, used by Alembic.
revision = '697e41afa2a'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_url', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company_url')
    ### end Alembic commands ###
